name: Create git tag, run scans and tests on Rust repos

on:
  push:
    branches:
      - master

env:
  AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
  AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
  AWS_REGION: 'eu-central-1'

jobs:
  set-gh-outputs:
    name: Set Github Outputs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Set semantic_version
        id: branch_check
        run: |
          semantic_version=$(cat version)
          echo "semantic_version=$semantic_version" >> $GITHUB_OUTPUT
      - name: Print Semantic version
        run: echo "semantic_version for branch '${{ github.base_ref }}' is '${{ steps.branch_check.outputs.semantic_version }}'"
    outputs:
      semantic_version: ${{ steps.branch_check.outputs.semantic_version }}
  # Test, scan, build and push Rust related repos or compiled binaries
  ci-ct-job-for-rust-repos:
    runs-on: ubuntu-latest
    needs: [set-gh-outputs]
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Render template
        run: |
          template_file="templates/secrets.template.cfg"
          output_file="secrets.cfg"
          cat $template_file | sed "s+PLACEHOLDER_AWS_ACCESS_KEY_ID+${{ env.AWS_ACCESS_KEY_ID }}+g" > $output_file
          sed -i "s+PLACEHOLDER_AWS_SECRET_ACCESS_KEY+${{ env.AWS_SECRET_ACCESS_KEY }}+g" $output_file
          sed -i "s+PLACEHOLDER_AWS_REGION+${{ env.AWS_REGION }}+g" $output_file
          sed -i "s+PLACEHOLDER_AWS_BUCKET_NAME+sample-bucket7000+g" $output_file
        working-directory: ./  
      - name: Test Rust repository
        uses: MGTheTrain/public-github-actions/.github/actions/test-rust-repository@main
        with:
          WORKING_DIRECTORY: ./
  create-git-tags-from-version-file-job:
    runs-on: ubuntu-latest
    needs: [set-gh-outputs]
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Create git tag from version file
        uses: MGTheTrain/public-github-actions/.github/actions/create-git-tag-from-version-file@main
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}